import { User, Form, FormConfig, Submission } from '@/types';

// モックユーザー
export const mockUser: User = {
  id: 'user-1',
  email: 'demo@example.com',
  name: 'デモユーザー',
  created_at: new Date().toISOString(),
};

// モックフォーム（複数）
export const mockForms: Form[] = [
  {
    id: 'form-1',
    user_id: 'user-1',
    name: 'お問い合わせフォーム',
    site_url: 'https://example.com',
    api_key: 'fb_a1b2c3d4e5f6g7h8',
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'form-2',
    user_id: 'user-1',
    name: '採用応募フォーム',
    site_url: 'https://example.com/careers',
    api_key: 'fb_x9y8z7w6v5u4t3s2',
    is_active: true,
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 'form-3',
    user_id: 'user-1',
    name: '資料請求フォーム',
    site_url: 'https://example.com/download',
    api_key: 'fb_m3n4o5p6q7r8s9t0',
    is_active: false,
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
];

// フォーム設定
export const mockFormConfigs: Record<string, FormConfig> = {
  'form-1': {
    id: 'config-1',
    form_id: 'form-1',
    enable_url_detection: true,
    enable_paste_detection: true,
    threshold_sales: 0.7,
    threshold_spam: 0.85,
    banned_keywords: ['営業', 'セールス', '販売促進', '広告代理店', '無料'],
    allowed_domains: [],
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  'form-2': {
    id: 'config-2',
    form_id: 'form-2',
    enable_url_detection: true,
    enable_paste_detection: false,
    threshold_sales: 0.8,
    threshold_spam: 0.9,
    banned_keywords: ['スカウト', '人材紹介', '採用代行'],
    allowed_domains: [],
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
  },
  'form-3': {
    id: 'config-3',
    form_id: 'form-3',
    enable_url_detection: false,
    enable_paste_detection: false,
    threshold_sales: 0.75,
    threshold_spam: 0.85,
    banned_keywords: [],
    allowed_domains: [],
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
};

// モック送信データ
export const mockSubmissions: Submission[] = [
  {
    id: 'sub-1',
    form_id: 'form-1',
    status: 'blocked',
    score_sales: 0.92,
    score_spam: 0.45,
    final_decision: 'block',
    content: {
      name: '営業太郎',
      email: 'sales@marketing-agency.com',
      message: '貴社のマーケティング支援サービスをご提案させていただきたく、ご連絡いたしました。弊社は広告代理店として多数の実績がございます。https://our-service.com をご覧ください。',
    },
    metadata: {
      url: 'https://example.com/contact',
      user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      timestamp: Date.now() - 3600000,
    },
    detection_reasons: ['url_detected', 'sales_keywords', 'paste_detected'],
    llm_reasoning: '明確な営業目的の提案メッセージです。自社サービスへの誘導リンクが含まれており、典型的なB2B営業メールの特徴を持っています。',
    ip_address: '203.0.113.45',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'sub-2',
    form_id: 'form-1',
    status: 'challenged',
    score_sales: 0.75,
    score_spam: 0.3,
    final_decision: 'challenge',
    content: {
      name: '佐藤健二',
      email: 'sato@business.co.jp',
      message: '御社のサービスについて詳しく知りたいのですが、資料をいただくことは可能でしょうか?',
    },
    metadata: {
      url: 'https://example.com/contact',
      user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      timestamp: Date.now() - 7200000,
    },
    detection_reasons: ['sales_keywords'],
    llm_reasoning: '「御社」という言葉と資料請求という内容から、営業目的の可能性がありますが、正当な問い合わせの可能性も残っています。',
    ip_address: '198.51.100.23',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'sub-3',
    form_id: 'form-1',
    status: 'allowed',
    score_sales: 0.15,
    score_spam: 0.1,
    final_decision: 'allow',
    content: {
      name: '田中花子',
      email: 'hanako@personal.jp',
      message: '先日購入した製品について質問があります。取扱説明書に記載されていない使い方について教えてください。',
    },
    metadata: {
      url: 'https://example.com/contact',
      user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)',
      timestamp: Date.now() - 10800000,
    },
    detection_reasons: [],
    llm_reasoning: '製品に関する正当な問い合わせです。営業目的やスパムの要素は見られません。',
    ip_address: '192.0.2.100',
    user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    updated_at: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: 'sub-4',
    form_id: 'form-2',
    status: 'blocked',
    score_sales: 0.88,
    score_spam: 0.72,
    final_decision: 'block',
    content: {
      name: '人材紹介太郎',
      email: 'recruiter@agency.com',
      message: '優秀な人材をご紹介させていただきます。弊社は人材紹介会社として、多数のマッチング実績がございます。',
    },
    metadata: {
      url: 'https://example.com/careers',
      user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      timestamp: Date.now() - 14400000,
    },
    detection_reasons: ['sales_keywords'],
    llm_reasoning: '人材紹介サービスの営業メールです。採用フォームへの営業目的の送信と判定されます。',
    ip_address: '203.0.113.200',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'sub-5',
    form_id: 'form-1',
    status: 'allowed',
    score_sales: 0.2,
    score_spam: 0.05,
    final_decision: 'allow',
    content: {
      name: '山本美咲',
      email: 'yamamoto@example.jp',
      message: 'サービスの利用方法について教えてください。',
    },
    metadata: {
      url: 'https://example.com/contact',
      user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      timestamp: Date.now() - 18000000,
    },
    detection_reasons: [],
    ip_address: '192.0.2.150',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    created_at: new Date(Date.now() - 18000000).toISOString(),
    updated_at: new Date(Date.now() - 18000000).toISOString(),
  },
];
